### ISSUE TITLE
python binding

### ISSUE THREAD

**Issue by topikachu** [ev3dev/ev3dev-lang#3]
Hi,
This is not a really issue. ^^  
I create a python project [python-ev3](https://github.com/topikachu/python-ev3) running on ev3dev.  
Are you willing to take a look?

Thanks

**Comment by rhempel** [comment]
I have looked at autogen - nice bit of work @WasabiFan! With respect to the Python bindings, would it be helpful to have a separate pure Python binding? As I understand it the current one builds on top of the C++ file handlers - or am I mistaken?

**Comment by ddemidov** [comment]
The python bindings in the official repo are indeed based on the C++ bindings. I gave a bit of motivation for this in #34. The only comparison between my and @topikachu's versions of python bindings I could find is this one: https://github.com/ev3con/python-ev3con/tree/master/linienverfolgung/alternativ. It seems to second my initial guess that C++ based bindings should be a bit faster than pure python (see the comment headers for those two files). Its in German though and I don't speak the language.

**Comment by rhempel** [comment]
OK, so do you mind if I also put together a pure Python set of bindings (the API will of course be the same anyways) I am doing some experiments with caching file handles to get around performance issues. Typically you access a bunch of attributes once for setup, then read/write the same handful during normal operation, so caching based on frequency or last used time may give us some real benefits.

**Comment by G33kDude** [comment]
There's a very large difference between caching and not caching the file handles. Without caching I couldn't get my gyro bot to balance. With caching everything ran much faster, and it balanced much more easily.

**Comment by ddemidov** [comment]
> OK, so do you mind if I also put together a pure Python set of bindings

Sure, why not. If the performance turns out to be adequate, I would not even mind replacing the C++ base with pure python implementation. The development cycle of anything C++ based for ev3dev  turned out to be a bit of a PITA due to hardware limitations and performance issues of cross-compilation environment.

Since the majority of the code today is generated with @WasabiFan's autogen script, switching the base should be painless.

**Comment by G33kDude** [comment]
What do we define as adequate though? I'd imagine we would want the best performance reasonably possible, and I would assume that wrapping the C++ binding would give that. If not for very straightforward actions like enable motor A, but at least for more complicated actions like drawing to the LCD.

If we do switch to "adequate" pure python bindings, it'd be a shame if it turns out the C++ wrapper was more performant and it falls out of development.

**Comment by ddemidov** [comment]
Another point for the pure python solution is the ability to easily install the bindings anywhere without the need for C++ compiler. Several users raised this question recently having desktop IDEs in mind.

**Comment by ddemidov** [comment]
> What do we define as adequate though?

Since the interfaces would be interchangeable, it should be easy to provide some performance tests. Then I think it would be easy to decide either way.

**Comment by WasabiFan** [comment]
@ddemidov Now that @rhempel is making a pure-python binding, I think we should rename your submodule in this repo to something that differentiates it from the other. I'm thinking that the name `native-python` would work, to go along with @rhempel's [`pure-python`](https://github.com/ev3dev/ev3dev-lang/tree/pure-python). Do you have any other ideas? I just want to make the differences clear so that someone attempting to decide what to use won't be confused when looking at the repo.

**Comment by ddemidov** [comment]
To my ear `native-python` sounds the same as `pure-python`. May be `cpp-python` would be more accurate, or we could just describe each version clearly in the README.
Also, I would not mind merging the versions if @rhempel's experiments with caching file access turn successful, as most of the points I made in #34 are moot since the introduction of the autogen script.

**Comment by ddemidov** [comment]
We could also merge the cpp and python (the cpp-based ones) bindings into a single submodule, since changing the one usually leads to a change (or at least to rebuilding) of another. Then we would have a cpp binding that incidentally also provides a python interface.

**Comment by rhempel** [comment]
I agree `native-python` and `pure-python` sound like they might mean the same thing. Let me see how the file caching goes - the whole point of this ev3dev exercise was to use the scripting language's native file i/o capabilities so we would not need low level C bindings for each language :-)

**Comment by ddemidov** [comment]
I've created a simple test (measure time needed to take 1000 readings of a motor position) for the C++, python, and pure-python bindings. The pure-python bindings were at adeb4bc2f34992e9de874a332f29ed2c52118e1f at the time of the test. The source code of the test versions: https://gist.github.com/ddemidov/e27fdf63f3ff6bb98dcf.

Here are the results:

### C++

```
$ ./perf_motor
lego-ev3-l-motor, outA
1000 readings in 160784 us
```

### Python

```
$ ./perf_motor.py 
lego-ev3-l-motor, outA
1000 readings in 0.365907 seconds
```

### Pure Python

```
$ ./perf_motor_pp.py 
Got a match outA <-> outA
/sys/class/tacho-motor/motor0
lego-ev3-l-motor, outA
1000 readings in 1.701115 seconds
```

So currently Python is 2.27 times slower than C++, and Pure Python is 4.65 times slower than Python (and 10.58 times slower that C++).

**Comment by rhempel** [comment]
I still have some debug code in there (obviously) but the results are not too terrible :-) I'm  not so much concerned with how much slower `pure-python` is. It's more important to be useable.
But it's good to have the performance benchmarks anyways!

**Comment by ddemidov** [comment]
Is it OK to provide some feedback at this point, or should I wait for a pull request?

It seems you have single file handle cache both for reading and writing attributes. When you have an IOError, you reopen the file: https://github.com/ev3dev/ev3dev-lang/blob/adeb4bc2f34992e9de874a332f29ed2c52118e1f/pure-python/ev3dev/ev3dev.py#L91-L110

So I think if I modify the test to measure both read and write of the same attribute, pure python will loose  the performance gain it got from file caching. It will probably be even slower than straightforward implementation without any caching (due to error handling). A simple solution would be to have two caches: one for reading and the other for writing.

EDIT: I just noticed that when you reopen the file, you do it both for reading and writing, so an IOError is probably a one time thing.

**Comment by rhempel** [comment]
Feedback is fine and appreciated - I don't normally program in Python.
What I was trying to accomplish was to isolate knowledge of the read/write nature of the property from the getters and setters. the first time you get an attribute the file is opened read only and is cached. Later, if you want to write to the attribute, the file is clodes and opened in `w+` mode. That way there is only a penalty the first time, after that the file is always read/writeable.
I guess we could consider two caches, but then you might run into a file handle limit. I may still need to deal with that.

**Comment by ddemidov** [comment]
Yes, I got the intention (see the edit to my above comment).

Re file handle limit: there is a builtin decorator [functools.lru_cache](https://docs.python.org/3/library/functools.html#functools.lru_cache) which looks very nice, but is only available in python3. [cachetools](http://pythonhosted.org/cachetools/) is a backport for python2.

**Comment by ddemidov** [comment]
It looks like [_get_string_array_attribute()](https://github.com/ev3dev/ev3dev-lang/blob/adeb4bc2f34992e9de874a332f29ed2c52118e1f/pure-python/ev3dev/ev3dev.py#L132-L133) returns single string instead of string array. `return self._get_attribute( attribute ).split()` would return an iterable list of strings.

**Comment by rhempel** [comment]
`_get_string_array_attribute` does return the entire string returned from the file - is it supposed to be iterable on return? If yes, then I'll split it before the return

**Comment by ddemidov** [comment]
A list of strings could be used like this:

``` py
# test sensor modes:
for m in sen.modes:
  m.mode = m
```

``` py
# check if command is supported:
if 'run-timed' in mot.commands:
  mot.command = 'run-timed'
else:
  mot.command = 'run-forever'
  sleep(42)
  mot.command = 'stop'
```

**Comment by rhempel** [comment]
There is no doubt it's useful - the question is whether the spec says that we want to return an iterable data structure or the entire string :-)
We could have rewritten the above example using `sen.modes.split()` - so I think we need consensus on what our language API needs to return for `string array` properties. My preference is to return the entire string and let the caller handle manipulating the result - but I am happy to discuss options.

**Comment by ddemidov** [comment]
Looks like the [`__EV3_MODULE_connected__`](https://github.com/ev3dev/ev3dev-lang/blob/pure-python/pure-python/ev3dev/ev3dev.py#L66-L67) dict is never cleared. What happens when a class holding a connected device is destroyed (e.g. goes out of scope)? Do you loose the ability to control the device until program restart?

**Comment by rhempel** [comment]
Yes, I'm running into that now after running tests :-) I need to have a destructor that iterates through the cache and closes the file handles.

**Comment by ddemidov** [comment]
Re string array splitting: I agree this may be a matter of interpretation. I just assumed that the strings should be splitted because that is the way all other bindings are working.
